# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.core.validators
import django.db.models.deletion
import mptt.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS pour l'icône", max_length=50, verbose_name='Icône')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='restaurants.category', verbose_name='Catégorie parent')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du restaurant')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.CharField(blank=True, max_length=255, verbose_name='Logo')),
                ('cover_image', models.CharField(blank=True, max_length=255, verbose_name='Image de couverture')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('country', models.CharField(default='Togo', max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('opening_hours', models.JSONField(default=dict, help_text='Format: {"lundi": {"open": "08:00", "close": "22:00", "closed": false}, ...}', verbose_name="Horaires d'ouverture")),
                ('delivery_radius', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Rayon de livraison (km)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2.5, max_digits=6, verbose_name='Frais de livraison')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Montant minimum de commande')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Restaurant vedette')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('categories', models.ManyToManyField(related_name='restaurants', to='restaurants.category', verbose_name='Catégories')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-is_featured', '-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('appetizer', 'Entrée'), ('main', 'Plat principal'), ('dessert', 'Dessert'), ('drink', 'Boisson'), ('side', 'Accompagnement')], max_length=20, verbose_name='Catégorie')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('ingredients', models.TextField(blank=True, verbose_name='Ingrédients')),
                ('allergens', models.JSONField(blank=True, default=list, help_text='Liste des allergènes présents', verbose_name='Allergènes')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories')),
                ('customization_options', models.JSONField(blank=True, default=dict, help_text='Options disponibles pour personnaliser le plat', verbose_name='Options de personnalisation')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Plat populaire')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Épicé')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Végétarien')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Végan')),
                ('is_halal', models.BooleanField(default=False, verbose_name='Halal')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de remise')),
                ('preparation_time', models.PositiveIntegerField(default=15, verbose_name='Temps de préparation (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Élément du menu',
                'verbose_name_plural': 'Éléments du menu',
                'ordering': ['category', 'name'],
                'unique_together': {('restaurant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Image vedette')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Image de restaurant',
                'verbose_name_plural': 'Images de restaurants',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('offer_type', models.CharField(choices=[('percentage', 'Pourcentage de remise'), ('fixed_amount', 'Montant fixe'), ('buy_one_get_one', 'Achetez-en un, obtenez-en un'), ('free_delivery', 'Livraison gratuite')], max_length=20, verbose_name="Type d'offre")),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valeur de la remise')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant minimum de commande')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Utilisations maximum')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('applicable_days', models.JSONField(default=list, help_text='Liste des jours : ["monday", "tuesday", ...]', verbose_name='Jours applicables')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('applicable_items', models.ManyToManyField(blank=True, related_name='special_offers', to='restaurants.menuitem', verbose_name='Éléments concernés')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Offre spéciale',
                'verbose_name_plural': 'Offres spéciales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Gestionnaire'), ('chef', 'Chef'), ('waiter', 'Serveur'), ('cashier', 'Caissier')], max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('can_manage_menu', models.BooleanField(default=False, verbose_name='Peut gérer le menu')),
                ('can_manage_orders', models.BooleanField(default=True, verbose_name='Peut gérer les commandes')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='Peut voir les statistiques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel de restaurant',
                'verbose_name_plural': 'Personnel de restaurants',
                'unique_together': {('restaurant', 'user')},
            },
        ),
    ]
