# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tmoney', 'Tmoney'), ('flooz', 'Flooz'), ('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money')], max_length=50, unique=True, verbose_name='Nom')),
                ('display_name', models.CharField(max_length=100, verbose_name="Nom d'affichage")),
                ('logo', models.CharField(blank=True, max_length=255, verbose_name='Logo')),
                ('api_endpoint', models.URLField(verbose_name='Endpoint API')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='Clé API')),
                ('api_secret', models.CharField(blank=True, max_length=200, verbose_name='Secret API')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10, verbose_name='Montant maximum')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Frais fixes')),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Frais en pourcentage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='Mode test')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('supported_countries', models.ManyToManyField(related_name='payment_providers', to='core.country', verbose_name='Pays supportés')),
            ],
            options={
                'verbose_name': 'Fournisseur de paiement mobile',
                'verbose_name_plural': 'Fournisseurs de paiement mobile',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('payment_method', models.CharField(choices=[('stripe_card', 'Carte bancaire (Stripe)'), ('stripe_paypal', 'PayPal'), ('tmoney', 'Tmoney'), ('flooz', 'Flooz'), ('cash_on_delivery', 'Paiement à la livraison'), ('wallet', 'Portefeuille GourmetGuide')], max_length=20, verbose_name='Méthode de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé'), ('partially_refunded', 'Partiellement remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('external_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID paiement externe')),
                ('external_customer_id', models.CharField(blank=True, max_length=200, verbose_name='ID client externe')),
                ('payment_metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées de paiement')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé')),
                ('refund_reason', models.TextField(blank=True, verbose_name='Raison du remboursement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Échoué le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobilePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du client')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID transaction fournisseur')),
                ('provider_reference', models.CharField(blank=True, max_length=200, verbose_name='Référence fournisseur')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse du fournisseur')),
                ('is_callback_received', models.BooleanField(default=False, verbose_name='Callback reçu')),
                ('callback_data', models.JSONField(blank=True, default=dict, verbose_name='Données de callback')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='Initié le')),
                ('callback_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Callback reçu le')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.mobilepaymentprovider')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_transaction', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Transaction de paiement mobile',
                'verbose_name_plural': 'Transactions de paiement mobile',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('stripe_card', 'Carte bancaire'), ('tmoney', 'Tmoney'), ('flooz', 'Flooz')], max_length=20, verbose_name='Type de méthode')),
                ('display_name', models.CharField(max_length=100, verbose_name="Nom d'affichage")),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='ID externe')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('is_default', models.BooleanField(default=False, verbose_name='Méthode par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('tmoney', 'Tmoney'), ('flooz', 'Flooz')], max_length=20, verbose_name='Fournisseur')),
                ('event_type', models.CharField(max_length=100, verbose_name="Type d'événement")),
                ('event_id', models.CharField(max_length=200, unique=True, verbose_name="ID d'événement")),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('processing', 'En cours de traitement'), ('processed', 'Traité'), ('failed', 'Échoué'), ('ignored', 'Ignoré')], default='received', max_length=20, verbose_name='Statut')),
                ('processing_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives de traitement')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Webhook de paiement',
                'verbose_name_plural': 'Webhooks de paiements',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant à rembourser')),
                ('reason', models.CharField(choices=[('customer_request', 'Demande du client'), ('order_cancelled', 'Commande annulée'), ('delivery_failed', 'Échec de livraison'), ('quality_issue', 'Problème de qualité'), ('duplicate_payment', 'Paiement en double'), ('technical_error', 'Erreur technique'), ('other', 'Autre')], max_length=30, verbose_name='Raison')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('external_refund_id', models.CharField(blank=True, max_length=200, verbose_name='ID remboursement externe')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Solde')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=8, verbose_name='Limite quotidienne')),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Limite mensuelle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='Gelé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit'), ('refund', 'Remboursement'), ('bonus', 'Bonus'), ('penalty', 'Pénalité')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('description', models.TextField(verbose_name='Description')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde après transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Transaction de portefeuille',
                'verbose_name_plural': 'Transactions de portefeuilles',
                'ordering': ['-created_at'],
            },
        ),
    ]
