# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assignée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('picked_up', 'Récupérée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='assigned', max_length=20, verbose_name='Statut')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigné le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepté le')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Récupéré le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de récupération estimée')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de livraison estimée')),
                ('distance_to_restaurant', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Distance jusqu'au restaurant (km)")),
                ('distance_to_customer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Distance jusqu'au client (km)")),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Notes de livraison')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du refus')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Attribution de livraison',
                'verbose_name_plural': 'Attributions de livraisons',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note de livraison')),
                ('punctuality_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note de ponctualité')),
                ('politeness_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note de politesse')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('reported_issues', models.JSONField(blank=True, default=list, help_text='Liste des problèmes : retard, nourriture froide, etc.', verbose_name='Problèmes signalés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Retour de livraison',
                'verbose_name_plural': 'Retours de livraisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('vehicle_breakdown', 'Panne de véhicule'), ('weather', 'Conditions météo'), ('traffic', 'Embouteillages'), ('customer_unavailable', 'Client indisponible'), ('wrong_address', 'Adresse incorrecte'), ('food_spilled', 'Nourriture renversée'), ('other', 'Autre')], max_length=30, verbose_name="Type d'incident")),
                ('description', models.TextField(verbose_name='Description')),
                ('incident_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Latitude de l'incident")),
                ('incident_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Longitude de l'incident")),
                ('incident_photos', models.JSONField(blank=True, default=list, verbose_name="Photos de l'incident")),
                ('status', models.CharField(choices=[('reported', 'Signalé'), ('investigating', "En cours d'investigation"), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='reported', max_length=20, verbose_name='Statut')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Signalé le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
            ],
            options={
                'verbose_name': 'Incident de livraison',
                'verbose_name_plural': 'Incidents de livraisons',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_delivery_time', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Temps de livraison moyen (minutes)')),
                ('average_pickup_time', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Temps de récupération moyen (minutes)')),
                ('total_distance_covered', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distance totale parcourue (km)')),
                ('average_distance_per_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Distance moyenne par livraison (km)')),
                ('on_time_deliveries', models.PositiveIntegerField(default=0, verbose_name="Livraisons à l'heure")),
                ('late_deliveries', models.PositiveIntegerField(default=0, verbose_name='Livraisons en retard')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gains totaux')),
                ('calculation_period_start', models.DateField(verbose_name='Début de période')),
                ('calculation_period_end', models.DateField(verbose_name='Fin de période')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Performance de livreur',
                'verbose_name_plural': 'Performances de livreurs',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de permis')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Vélo'), ('motorbike', 'Moto'), ('car', 'Voiture'), ('scooter', 'Scooter'), ('walking', 'À pied')], max_length=20, verbose_name='Type de véhicule')),
                ('vehicle_registration', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('identity_document', models.CharField(blank=True, max_length=255, verbose_name="Pièce d'identité")),
                ('license_document', models.CharField(blank=True, max_length=255, verbose_name='Permis de conduire')),
                ('vehicle_insurance', models.CharField(blank=True, max_length=255, verbose_name='Assurance véhicule')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('offline', 'Hors ligne'), ('break', 'En pause')], default='offline', max_length=20, verbose_name='Statut')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude actuelle')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude actuelle')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour de position')),
                ('max_delivery_radius', models.PositiveIntegerField(default=10, verbose_name='Rayon de livraison maximum (km)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Livraisons totales')),
                ('successful_deliveries', models.PositiveIntegerField(default=0, verbose_name='Livraisons réussies')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Heure de début')),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin estimée')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin réelle')),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance totale (km)')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (minutes)')),
                ('is_optimized', models.BooleanField(default=False, verbose_name='Optimisé')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Itinéraire de livraison',
                'verbose_name_plural': 'Itinéraires de livraisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRouteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(verbose_name='Ordre dans la séquence')),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée estimée")),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée réelle")),
            ],
            options={
                'verbose_name': 'Commande dans itinéraire',
                'verbose_name_plural': 'Commandes dans itinéraires',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude du centre')),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude du centre')),
                ('radius', models.PositiveIntegerField(default=5, verbose_name='Rayon (km)')),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Frais de livraison')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['city', 'name'],
            },
        ),
    ]
