# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_feedback', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryincident',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_incidents', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryincident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='working_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_persons', to='core.city'),
        ),
        migrations.AddField(
            model_name='deliveryperformance',
            name='delivery_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='delivery.deliveryperson'),
        ),
        migrations.AddField(
            model_name='deliveryincident',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='delivery.deliveryperson'),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='delivery.deliveryperson'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='delivery.deliveryperson'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delivery.deliveryperson'),
        ),
        migrations.AddField(
            model_name='deliveryrouteorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_positions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryrouteorder',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_orders', to='delivery.deliveryroute'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='orders',
            field=models.ManyToManyField(related_name='delivery_routes', through='delivery.DeliveryRouteOrder', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='assigned_delivery_persons',
            field=models.ManyToManyField(blank=True, related_name='assigned_zones', to='delivery.deliveryperson', verbose_name='Livreurs assignés'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='core.city'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryrouteorder',
            unique_together={('route', 'order')},
        ),
    ]
