# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code ISO')),
                ('phone_prefix', models.CharField(max_length=5, verbose_name='Préfixe téléphonique')),
                ('currency_code', models.CharField(default='XOF', max_length=3, verbose_name='Code devise')),
                ('currency_symbol', models.CharField(default='CFA', max_length=5, verbose_name='Symbole devise')),
                ('supports_tmoney', models.BooleanField(default=False, verbose_name='Support Tmoney')),
                ('supports_flooz', models.BooleanField(default=False, verbose_name='Support Flooz')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Général'), ('ordering', 'Commandes'), ('payment', 'Paiements'), ('delivery', 'Livraison'), ('restaurant', 'Restaurants'), ('account', 'Compte')], max_length=20, verbose_name='Catégorie')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='Langue')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GourmetGuide', max_length=100, verbose_name='Nom du site')),
                ('site_description', models.TextField(blank=True, verbose_name='Description du site')),
                ('site_logo', models.CharField(blank=True, max_length=255, verbose_name='Logo du site')),
                ('site_favicon', models.CharField(blank=True, max_length=255, verbose_name='Favicon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de support')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=2.5, max_digits=6, verbose_name='Frais de livraison par défaut')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Montant minimum de commande')),
                ('max_delivery_radius', models.PositiveIntegerField(default=15, verbose_name='Rayon de livraison maximum (km)')),
                ('loyalty_points_per_euro', models.PositiveIntegerField(default=10, verbose_name='Points de fidélité par euro')),
                ('loyalty_euro_per_point', models.DecimalField(decimal_places=3, default=0.01, max_digits=4, verbose_name='Valeur en euro par point')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de taxe (%)')),
                ('enable_email_notifications', models.BooleanField(default=True, verbose_name='Activer les notifications email')),
                ('enable_sms_notifications', models.BooleanField(default=False, verbose_name='Activer les notifications SMS')),
                ('enable_push_notifications', models.BooleanField(default=True, verbose_name='Activer les notifications push')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Message de maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], max_length=10, verbose_name='Plateforme')),
                ('version_number', models.CharField(max_length=20, verbose_name='Numéro de version')),
                ('version_code', models.PositiveIntegerField(verbose_name='Code de version')),
                ('is_required', models.BooleanField(default=False, verbose_name='Mise à jour obligatoire')),
                ('release_notes', models.TextField(blank=True, verbose_name='Notes de version')),
                ('download_url', models.URLField(blank=True, verbose_name='URL de téléchargement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('released_at', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
            ],
            options={
                'verbose_name': "Version de l'application",
                'verbose_name_plural': "Versions de l'application",
                'ordering': ['-version_code'],
                'unique_together': {('platform', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('general', 'Question générale'), ('technical', 'Problème technique'), ('billing', 'Facturation'), ('restaurant', 'Restaurant'), ('delivery', 'Livraison'), ('complaint', 'Plainte'), ('suggestion', 'Suggestion')], max_length=20, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='new', max_length=20, verbose_name='Statut')),
                ('admin_response', models.TextField(blank=True, verbose_name='Réponse admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('coverage_radius', models.PositiveIntegerField(default=20, verbose_name='Rayon de couverture (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
