# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemstats',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='restaurants.menuitem'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['metric_type', '-recorded_at'], name='analytics_p_metric__1e5b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['endpoint', '-recorded_at'], name='analytics_p_endpoin_fc87de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='popularityindex',
            unique_together={('entity_type', 'entity_id', 'calculation_date')},
        ),
        migrations.AddField(
            model_name='restaurantstats',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='clicked_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='related_menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_interactions', to='restaurants.menuitem'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_interactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='related_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_interactions', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customersegmentmembership',
            unique_together={('user', 'segment')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitemstats',
            unique_together={('menu_item', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantstats',
            unique_together={('restaurant', 'date')},
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query', '-searched_at'], name='analytics_s_query_ffbcc5_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_4c311e_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['action', '-timestamp'], name='analytics_u_action_504a09_idx'),
        ),
    ]
