# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('double_points', 'Double points'), ('triple_points', 'Triple points'), ('bonus_points', 'Points bonus'), ('free_delivery', 'Livraison gratuite'), ('special_discount', 'Remise spéciale')], max_length=20, verbose_name="Type d'événement")),
                ('multiplier', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Multiplicateur')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='Points bonus')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pourcentage de remise')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant minimum')),
                ('tier_required', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or'), ('platinum', 'Platine'), ('diamond', 'Diamant')], max_length=20, verbose_name='Niveau requis')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Événement de fidélité',
                'verbose_name_plural': 'Événements de fidélité',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du programme')),
                ('description', models.TextField(verbose_name='Description')),
                ('points_per_euro', models.PositiveIntegerField(default=10, verbose_name='Points par euro')),
                ('bonus_multiplier', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Multiplicateur de bonus')),
                ('silver_threshold', models.PositiveIntegerField(default=500, verbose_name='Seuil Argent')),
                ('gold_threshold', models.PositiveIntegerField(default=2000, verbose_name='Seuil Or')),
                ('platinum_threshold', models.PositiveIntegerField(default=5000, verbose_name='Seuil Platine')),
                ('diamond_threshold', models.PositiveIntegerField(default=10000, verbose_name='Seuil Diamant')),
                ('tier_benefits', models.JSONField(default=dict, help_text='Configuration des avantages pour chaque niveau', verbose_name='Avantages par niveau')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Programme de fidélité',
                'verbose_name_plural': 'Programmes de fidélité',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='Image')),
                ('reward_type', models.CharField(choices=[('discount_percentage', 'Remise en pourcentage'), ('discount_fixed', 'Remise fixe'), ('free_delivery', 'Livraison gratuite'), ('free_item', 'Plat gratuit'), ('upgrade', 'Surclassement'), ('gift', 'Cadeau')], max_length=20, verbose_name='Type de récompense')),
                ('reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valeur de la récompense')),
                ('points_required', models.PositiveIntegerField(verbose_name='Points requis')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant minimum de commande')),
                ('tier_required', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or'), ('platinum', 'Platine'), ('diamond', 'Diamant')], max_length=20, verbose_name='Niveau requis')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rachats maximum')),
                ('max_redemptions_per_user', models.PositiveIntegerField(default=1, verbose_name='Rachats par utilisateur')),
                ('current_redemptions', models.PositiveIntegerField(default=0, verbose_name='Rachats actuels')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Récompense vedette')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Récompense de fidélité',
                'verbose_name_plural': 'Récompenses de fidélité',
                'ordering': ['-is_featured', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Gagnés'), ('redeemed', 'Utilisés'), ('expired', 'Expirés'), ('bonus', 'Bonus'), ('penalty', 'Pénalité'), ('refund', 'Remboursement')], max_length=20, verbose_name='Type de transaction')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('description', models.TextField(verbose_name='Description')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Solde après transaction')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Transaction de points',
                'verbose_name_plural': 'Transactions de points',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True, verbose_name='Code de parrainage')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('referrer_points_awarded', models.PositiveIntegerField(default=0, verbose_name='Points accordés au parrain')),
                ('referee_points_awarded', models.PositiveIntegerField(default=0, verbose_name='Points accordés au filleul')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_points', models.PositiveIntegerField(default=100, verbose_name='Points pour le parrain')),
                ('referee_points', models.PositiveIntegerField(default=50, verbose_name='Points pour le filleul')),
                ('referrer_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise pour le parrain')),
                ('referee_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise pour le filleul')),
                ('min_referee_order_amount', models.DecimalField(decimal_places=2, default=20.0, max_digits=8, verbose_name='Montant minimum première commande filleul')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Programme de parrainage',
                'verbose_name_plural': 'Programmes de parrainage',
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_code', models.CharField(max_length=20, unique=True, verbose_name='Code de rachat')),
                ('points_used', models.PositiveIntegerField(verbose_name='Points utilisés')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Racheté le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
            ],
            options={
                'verbose_name': 'Rachat de récompense',
                'verbose_name_plural': 'Rachats de récompenses',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de carte')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='Code QR')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Points totaux')),
                ('available_points', models.PositiveIntegerField(default=0, verbose_name='Points disponibles')),
                ('used_points', models.PositiveIntegerField(default=0, verbose_name='Points utilisés')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or'), ('platinum', 'Platine'), ('diamond', 'Diamant')], default='bronze', max_length=20, verbose_name='Niveau')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Commandes totales')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total dépensé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('customer', models.OneToOneField(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte de fidélité',
                'verbose_name_plural': 'Cartes de fidélité',
            },
        ),
    ]
