# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyevent',
            name='participating_restaurants',
            field=models.ManyToManyField(blank=True, related_name='loyalty_events', to='restaurants.restaurant', verbose_name='Restaurants participants'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='applicable_menu_items',
            field=models.ManyToManyField(blank=True, related_name='loyalty_rewards', to='restaurants.menuitem', verbose_name='Plats applicables'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='applicable_restaurants',
            field=models.ManyToManyField(blank=True, related_name='loyalty_rewards', to='restaurants.restaurant', verbose_name='Restaurants applicables'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='loyalty_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='loyalty.loyaltycard'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='related_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='loyalty.loyaltyreward'),
        ),
        migrations.AddField(
            model_name='referral',
            name='completed_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completing_referrals', to='orders.order'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='loyalty.referralprogram'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='loyalty_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='loyalty.loyaltycard'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='order_used_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyreward'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referee')},
        ),
    ]
