# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('positive', 'Positif'), ('negative', 'Négatif'), ('neutral', 'Neutre')], max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('suggested_overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note globale suggérée')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Template d'avis",
                'verbose_name_plural': "Templates d'avis",
                'ordering': ['category', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note globale')),
                ('food_quality_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualité de la nourriture')),
                ('service_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Service')),
                ('delivery_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Livraison')),
                ('value_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rapport qualité/prix')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('images', models.JSONField(blank=True, default=list, help_text='URLs des images uploadées', verbose_name='Images')),
                ('status', models.CharField(choices=[('pending', 'En attente de modération'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('hidden', 'Masqué')], default='pending', max_length=20, verbose_name='Statut')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='Notes de modération')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de "utile"')),
                ('reported_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de signalements')),
                ('restaurant_response', models.TextField(blank=True, verbose_name='Réponse du restaurant')),
                ('restaurant_response_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
                ('restaurant_responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'restaurant', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='reviews.review')),
            ],
            options={
                'verbose_name': "Image d'avis",
                'verbose_name_plural': "Images d'avis",
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('taste_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Goût')),
                ('presentation_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Présentation')),
                ('portion_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Portion')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('taste_tags', models.JSONField(blank=True, default=list, help_text='Tags : délicieux, épicé, salé, sucré, etc.', verbose_name='Tags de goût')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Recommanderait')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Achat vérifié')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de "utile"')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.menuitem')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Avis de plat',
                'verbose_name_plural': 'Avis de plats',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'menu_item', 'order_item')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True, verbose_name='Utile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote utile',
                'verbose_name_plural': 'Votes utiles',
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('fake', 'Faux avis'), ('inappropriate', 'Contenu inapproprié'), ('offensive', 'Contenu offensant'), ('irrelevant', 'Hors sujet'), ('personal_attack', 'Attaque personnelle'), ('other', 'Autre')], max_length=20, verbose_name='Raison')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes admin')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Signalé le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports_made', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reports_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Signalement d'avis",
                'verbose_name_plural': "Signalements d'avis",
                'ordering': ['-reported_at'],
                'unique_together': {('reporter', 'review')},
            },
        ),
    ]
