# Generated by Django 5.2.5 on 2025-08-10 21:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('customizations', models.JSONField(blank=True, default=dict, verbose_name='Personnalisations')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Élément du panier',
                'verbose_name_plural': 'Éléments du panier',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed_amount', 'Montant fixe'), ('free_delivery', 'Livraison gratuite')], max_length=20, verbose_name='Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la remise')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant minimum')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Remise maximum')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Utilisations maximum')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Utilisations par utilisateur')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant de la remise')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Utilisé le')),
            ],
            options={
                'verbose_name': 'Utilisation de coupon',
                'verbose_name_plural': 'Utilisations de coupons',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('picked_up', 'Récupérée par le livreur'), ('delivering', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('delivery_address', models.TextField(verbose_name='Adresse de livraison')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de livraison')),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de livraison')),
                ('delivery_instructions', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sous-total')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Frais de livraison')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant des taxes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant de la remise')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de livraison estimée')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de livraison réelle')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Notes du client')),
                ('restaurant_notes', models.TextField(blank=True, verbose_name='Notes du restaurant')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Notes du livreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('customizations', models.JSONField(blank=True, default=dict, help_text='Personnalisations choisies par le client', verbose_name='Personnalisations')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Élément de commande',
                'verbose_name_plural': 'Éléments de commandes',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='Statut précédent')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statuts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude actuelle')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude actuelle')),
                ('estimated_preparation_time', models.PositiveIntegerField(default=30, verbose_name='Temps de préparation estimé (minutes)')),
                ('estimated_delivery_time', models.PositiveIntegerField(default=30, verbose_name='Temps de livraison estimé (minutes)')),
                ('preparation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Préparation commencée à')),
                ('preparation_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Préparation terminée à')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de récupération')),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Livraison commencée à')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livrée à')),
                ('distance_to_customer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Distance jusqu'au client (km)")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Suivi de commande',
                'verbose_name_plural': 'Suivis de commandes',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('customer', models.OneToOneField(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
    ]
